version: '3.9'

services:
  postgres:
    container_name: fos_postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: fos_zipkin
    ports:
      - "9411:9411"
volumes:
  postgres:
networks:
  postgres:
    driver: bridge