server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/auth/**
        - id: food
          uri: lb://FOOD
          predicates:
            - Path=/api/food/**
          filters:
            - AuthPrefilter
  zipkin:
    base-url: http://localhost:9411
management:
  endpoints:
    web:
      exposure:
        include: gateway

  endpoint:
    gateway:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
