server:
  port: 8081
spring:
  application:
    name: food

  datasource:
    username: root
    password: password
    url: jdbc:postgresql://localhost:5432/food
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
logging:
  level:
    sql: debug
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.SQL: DEBUG
    org.hibernate.hql: debug
    org.hibernate.cache: debug
    org.hibernate.transaction: debug
    org.hibernate.tool.hbm2ddl: debug
  file:
    name: ${java.io.tmpdir}/${spring.application.name}.log
